export type Rarity = 'Common' | 'Uncommon' | 'Rare' | 'Very Rare' | 'Ultra Rare';

export interface GuppyStrain {
  id: string;
  name: string;
  rarity: Rarity;
  category: string;
  tailType: string;
  description: string;
  gradientFrom: string;
  gradientTo: string;
  traits: string[];
  wikiSearch: string;
  photoUrl?: string;  // direct URL when a real photo has been sourced
}

export const guppyStrains: GuppyStrain[] = [
  {
    id: 'wild-type',
    name: 'Wild-Type Guppy (Poecilia reticulata)',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Round/Fan',
    description: 'The original guppy from Trinidad — males display brilliant, unpredictable color patches across a compact fan tail. Every wild-type male is genetically unique; no two look exactly alike. The foundation from which all modern fancy strains were selectively bred.',
    gradientFrom: '#1B5E20',
    gradientTo: '#4CAF50',
    traits: ['Unique random color patches', 'Iridescent scales', 'Small fan tail', 'Foundation of all fancy strains'],
    wikiSearch: 'Poecilia reticulata wild male',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Guppy_Poecilia_reticulata.jpg/500px-Guppy_Poecilia_reticulata.jpg',
  },
  {
    id: 'delta-tail',
    name: 'Blue Delta Tail Fancy Guppy',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Delta/Fan',
    description: 'Electric blue body with a broad, triangular delta tail that fans out wide. The blue delta tail is one of the premier show-quality strains — breeders compete for the widest tail coverage and the deepest, most uniform blue body color.',
    gradientFrom: '#1565C0',
    gradientTo: '#42A5F5',
    traits: ['Electric blue body', 'Wide triangular delta tail', 'Show quality strain'],
    wikiSearch: 'blue delta tail guppy fancy male',
  },
  {
    id: 'veil-tail',
    name: 'Red Veil Tail Fancy Guppy',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Veil',
    description: 'Deep crimson red body with an elongated veil tail that drapes through the water like flowing silk. The red coloration intensifies toward the tail edges, making this one of the most visually dramatic of the classic tail types.',
    gradientFrom: '#C62828',
    gradientTo: '#EF9A9A',
    traits: ['Crimson red body', 'Long flowing veil tail', 'Silky dramatic movement'],
    wikiSearch: 'red veil tail guppy fancy male',
  },
  {
    id: 'round-tail',
    name: 'Green Round Tail Fancy Guppy',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Round',
    description: 'Iridescent green body with a perfectly circular, symmetrical tail. The round tail gives this strain a clean, balanced silhouette and the green coloration shifts from emerald to teal depending on light angle — a subtle but beautiful strain.',
    gradientFrom: '#1B5E20',
    gradientTo: '#66BB6A',
    traits: ['Iridescent green body', 'Perfectly circular tail', 'Color-shifting scales'],
    wikiSearch: 'green round tail guppy fancy male',
  },
  {
    id: 'double-sword-tail',
    name: 'Yellow Double Sword Tail Guppy',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Double Sword',
    description: 'Golden yellow body with twin sword-like extensions jutting from both the top and bottom of the tail, forming a dramatic X-shape. The yellow coloration makes the sword rays look like gleaming blades — a striking and unusual strain.',
    gradientFrom: '#F9A825',
    gradientTo: '#FFF176',
    traits: ['Golden yellow body', 'Twin sword tail extensions', 'X-shaped silhouette'],
    wikiSearch: 'yellow double sword tail guppy male',
  },
  {
    id: 'top-sword-tail',
    name: 'Blue Top Sword Tail Guppy',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Top Sword',
    description: 'Blue iridescent body with a single elongated sword ray shooting upward from the dorsal edge of the tail. The upswept sword combined with the blue body gives this strain an arrow-like profile unlike any other guppy.',
    gradientFrom: '#1565C0',
    gradientTo: '#64B5F6',
    traits: ['Blue iridescent body', 'Single upper sword ray', 'Arrow-like profile'],
    wikiSearch: 'blue top sword tail guppy male',
  },
  {
    id: 'bottom-sword-tail',
    name: 'Red Bottom Sword Tail Guppy',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Bottom Sword',
    description: 'Vivid red body with a single sword ray extending downward from the base of the tail. The red coloration makes the downward sweeping sword look especially bold — a distinctive and elegant strain.',
    gradientFrom: '#B71C1C',
    gradientTo: '#EF9A9A',
    traits: ['Vivid red body', 'Single lower sword ray', 'Elegant downward sweep'],
    wikiSearch: 'red bottom sword tail guppy male',
  },
  {
    id: 'lyretail',
    name: 'Red Lyretail Fancy Guppy',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Lyre',
    description: 'Fiery red body with a lyre-shaped tail — curved upper and lower lobes arch gracefully outward like the ancient stringed instrument. The red lyretail is one of the most elegant show strains, combining bold color with the most musically inspired tail form in the hobby.',
    gradientFrom: '#B71C1C',
    gradientTo: '#EF9A9A',
    traits: ['Fiery red body', 'Curved lyre-shaped tail lobes', 'Show quality'],
    wikiSearch: 'red lyretail guppy fancy male',
  },
  {
    id: 'spear-tail',
    name: 'Teal Spear Tail Guppy',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Spear',
    description: 'Teal-green iridescent body with a tail that tapers to a single sharp central point. The spear tail is the most minimalist of the classic tail forms, and the teal coloring intensifies toward the tip to emphasize the point.',
    gradientFrom: '#00695C',
    gradientTo: '#80CBC4',
    traits: ['Teal-green iridescent body', 'Sharp pointed spear tail', 'Minimalist profile'],
    wikiSearch: 'spear tail guppy teal green male',
  },
  {
    id: 'coffertail',
    name: 'Golden Coffertail Guppy',
    rarity: 'Rare',
    category: 'Classic Tail Types',
    tailType: 'Coffer',
    description: 'Gold and amber body with the rare coffertail shape — flat across the top edge and rounded on the bottom, like an ornate treasure chest lid. One of the rarest tail forms in the entire hobby, demanding both for its uniqueness and difficulty to breed true.',
    gradientFrom: '#FF8F00',
    gradientTo: '#FFD54F',
    traits: ['Gold & amber body', 'Flat-top rounded-bottom tail', 'Extremely rare tail form'],
    wikiSearch: 'coffertail guppy gold fancy male',
  },
  {
    id: 'pintail',
    name: 'Blue Steel Pintail Guppy',
    rarity: 'Rare',
    category: 'Classic Tail Types',
    tailType: 'Pin/Needle',
    description: 'Steel blue and gray body with a tail that tapers to an impossibly fine needle point. The pintail is the most minimalist of all guppy tail forms — a total departure from the flowing fan tails, making it a collector\'s curiosity.',
    gradientFrom: '#37474F',
    gradientTo: '#90A4AE',
    traits: ['Steel blue-gray body', 'Needle-fine tail point', 'Minimalist collector\'s strain'],
    wikiSearch: 'pintail needle tail guppy blue male',
  },
  {
    id: 'flag-tail',
    name: 'Red & Black Flag Tail Guppy',
    rarity: 'Rare',
    category: 'Classic Tail Types',
    tailType: 'Flag',
    description: 'Red body with black accents and a rectangular flag-shaped tail with a straight trailing edge. As the fish swims, the tail undulates like a banner in the current — the red and black combination makes this one of the most commanding flag tail variants.',
    gradientFrom: '#BF360C',
    gradientTo: '#FF8A65',
    traits: ['Red & black body', 'Rectangular flag-shaped tail', 'Straight trailing edge'],
    wikiSearch: 'red flag tail guppy fancy male',
  },
  {
    id: 'moscow-blue',
    name: 'Moscow Blue',
    rarity: 'Uncommon',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'Developed in Russia, this strain displays an intense solid blue body that shimmers like a night sky.',
    gradientFrom: '#0D47A1',
    gradientTo: '#1565C0',
    traits: ['Solid blue body', 'Russian strain', 'Intense coloration'],
    wikiSearch: 'Moscow Blue guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Guppy_pho_0048.jpg/500px-Guppy_pho_0048.jpg',
  },
  {
    id: 'moscow-green',
    name: 'Moscow Green',
    rarity: 'Uncommon',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'A rich, jewel-toned green body makes this Russian strain one of the most visually striking guppies available.',
    gradientFrom: '#1B5E20',
    gradientTo: '#2E7D32',
    traits: ['Solid green body', 'Jewel-toned', 'Russian origin'],
    wikiSearch: 'Moscow Green guppy',
  },
  {
    id: 'moscow-purple',
    name: 'Moscow Purple',
    rarity: 'Rare',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'A deep purple body, rare among fish. This Moscow strain commands attention in any tank.',
    gradientFrom: '#4A148C',
    gradientTo: '#6A1B9A',
    traits: ['Deep purple body', 'Head-to-tail color', 'Show quality'],
    wikiSearch: 'Moscow Purple guppy',
  },
  {
    id: 'black-moscow',
    name: 'Black Moscow',
    rarity: 'Rare',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'Nearly pitch black with a blue iridescent sheen. The Black Moscow is hauntingly beautiful and difficult to breed true.',
    gradientFrom: '#212121',
    gradientTo: '#1A237E',
    traits: ['Jet black body', 'Blue iridescence', 'Hard to breed true'],
    wikiSearch: 'Black Moscow guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Guppy_male_moscow.jpg/500px-Guppy_male_moscow.jpg',
  },
  {
    id: 'yellow-cobra',
    name: 'Yellow Cobra',
    rarity: 'Common',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Bright yellow with vertical snake-like markings on the body. Vibrant and eye-catching with the classic cobra pattern.',
    gradientFrom: '#F57F17',
    gradientTo: '#FFF176',
    traits: ['Yellow body', 'Snake markings', 'Vertical stripes'],
    wikiSearch: 'Yellow Cobra guppy snakeskin',
  },
  {
    id: 'red-cobra',
    name: 'Red Cobra',
    rarity: 'Common',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Fiery red with the distinctive cobra snakeskin pattern. Bold and aggressive-looking, a crowd favorite.',
    gradientFrom: '#B71C1C',
    gradientTo: '#EF5350',
    traits: ['Red body', 'Cobra pattern', 'Bold presence'],
    wikiSearch: 'Red Cobra guppy',
  },
  {
    id: 'green-cobra',
    name: 'Green Cobra',
    rarity: 'Uncommon',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Vivid green scales arranged in the cobra pattern. Like a tiny jungle serpent, exotic and vibrant.',
    gradientFrom: '#2E7D32',
    gradientTo: '#81C784',
    traits: ['Green scales', 'Cobra pattern', 'Exotic look'],
    wikiSearch: 'Green Cobra guppy',
  },
  {
    id: 'blue-cobra',
    name: 'Blue Cobra',
    rarity: 'Uncommon',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Electric blue with snake-like body markings. Cool, mysterious, and one of the most popular cobra varieties.',
    gradientFrom: '#1A237E',
    gradientTo: '#5C6BC0',
    traits: ['Blue body', 'Snake pattern', 'Electric sheen'],
    wikiSearch: 'Blue Cobra guppy',
  },
  {
    id: 'king-cobra',
    name: 'King Cobra',
    rarity: 'Rare',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'The regal king of cobra guppies. Combines deep purple and gold in an intricate snakeskin pattern fit for royalty.',
    gradientFrom: '#4A148C',
    gradientTo: '#FF8F00',
    traits: ['Purple & gold', 'Complex pattern', 'Royal appearance'],
    wikiSearch: 'King Cobra guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Cobra_Guppy_(Poecilia_reticulata).JPG/500px-Cobra_Guppy_(Poecilia_reticulata).JPG',
  },
  {
    id: 'blue-tuxedo',
    name: 'Blue Tuxedo',
    rarity: 'Common',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'The classic tuxedo pattern in blue: front half lighter, back half deep blue, like wearing formal attire.',
    gradientFrom: '#1A237E',
    gradientTo: '#0277BD',
    traits: ['Two-tone body', 'Tuxedo pattern', 'Blue coloration'],
    wikiSearch: 'Blue Tuxedo guppy',
  },
  {
    id: 'red-tuxedo',
    name: 'Red Tuxedo',
    rarity: 'Common',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'A bold red tuxedo pattern with a dark rear half. Dramatic contrast that makes this fish pop in any tank.',
    gradientFrom: '#B71C1C',
    gradientTo: '#4A148C',
    traits: ['Red & dark contrast', 'Tuxedo pattern', 'Bold look'],
    wikiSearch: 'Red Tuxedo guppy',
  },
  {
    id: 'yellow-tuxedo',
    name: 'Yellow Tuxedo',
    rarity: 'Uncommon',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'Sunny yellow front with a dark navy tuxedo back. Cheerful yet sophisticated, this is a show-stopper.',
    gradientFrom: '#F57F17',
    gradientTo: '#1A237E',
    traits: ['Yellow & navy', 'Tuxedo pattern', 'Cheerful colors'],
    wikiSearch: 'Yellow Tuxedo guppy',
  },
  {
    id: 'neon-tuxedo',
    name: 'Neon Tuxedo',
    rarity: 'Rare',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'The tuxedo pattern taken to the extreme with neon electric colors that seem to glow under aquarium lights.',
    gradientFrom: '#006064',
    gradientTo: '#00E5FF',
    traits: ['Neon coloration', 'Electric appearance', 'Glows under light'],
    wikiSearch: 'Neon Tuxedo guppy electric',
  },
  {
    id: 'half-black-blue',
    name: 'Half Black Blue',
    rarity: 'Uncommon',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'The rear half of the body is jet black, the front a vivid blue. A striking two-tone masterpiece.',
    gradientFrom: '#1A237E',
    gradientTo: '#424242',
    traits: ['Half black', 'Blue front', 'Sharp contrast'],
    wikiSearch: 'Half Black Blue guppy',
  },
  {
    id: 'half-black-red',
    name: 'Half Black Red',
    rarity: 'Uncommon',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'The classic half-black pattern in red. The fiery front against the black rear creates a dramatic fire-and-darkness look.',
    gradientFrom: '#B71C1C',
    gradientTo: '#212121',
    traits: ['Half black', 'Red front', 'Fire contrast'],
    wikiSearch: 'Half Black Red guppy',
  },
  {
    id: 'half-black-purple',
    name: 'Half Black Purple',
    rarity: 'Rare',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'Deep royal purple meets jet black in this striking half-black variety. Mysterious and regal.',
    gradientFrom: '#4A148C',
    gradientTo: '#212121',
    traits: ['Half black', 'Purple front', 'Regal look'],
    wikiSearch: 'Half Black Purple guppy',
  },
  {
    id: 'half-black-yellow',
    name: 'Half Black Yellow',
    rarity: 'Uncommon',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'Bright sunny yellow meets the dark abyss in this half-black strain. High contrast and visually stunning.',
    gradientFrom: '#F57F17',
    gradientTo: '#212121',
    traits: ['Half black', 'Yellow front', 'High contrast'],
    wikiSearch: 'Half Black Yellow guppy',
  },
  {
    id: 'half-black-pastel',
    name: 'Half Black Pastel',
    rarity: 'Rare',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'Soft pastel shades on the front half transition dramatically to solid black. Delicate yet striking.',
    gradientFrom: '#880E4F',
    gradientTo: '#212121',
    traits: ['Half black', 'Pastel colors', 'Soft to stark contrast'],
    wikiSearch: 'Half Black Pastel guppy',
  },
  {
    id: 'full-red',
    name: 'Full Red',
    rarity: 'Common',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'Entirely covered in vibrant red from nose to tail. A true red guppy with no other colors — simple perfection.',
    gradientFrom: '#C62828',
    gradientTo: '#E53935',
    traits: ['All red body', 'Uniform color', 'Show standard'],
    wikiSearch: 'Full Red guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Guppy_-_FullRed_-_male.jpg/500px-Guppy_-_FullRed_-_male.jpg',
  },
  {
    id: 'albino-full-red',
    name: 'Albino Full Red',
    rarity: 'Rare',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'The albino form of the Full Red — pink-red body with striking red eyes. Rare and uniquely beautiful.',
    gradientFrom: '#FF80AB',
    gradientTo: '#FF6090',
    traits: ['Albino form', 'Red eyes', 'Pink-red coloration'],
    wikiSearch: 'Albino Full Red guppy',
  },
  {
    id: 'platinum',
    name: 'Platinum (Full White)',
    rarity: 'Uncommon',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'A pristine, metallic white or platinum body that gleams like polished silver. Pure elegance.',
    gradientFrom: '#9E9E9E',
    gradientTo: '#ECEFF1',
    traits: ['Metallic white', 'Silver sheen', 'Pure elegance'],
    wikiSearch: 'Platinum White guppy',
  },
  {
    id: 'full-black',
    name: 'Full Black',
    rarity: 'Rare',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'Completely black from head to tail — one of the hardest colors to achieve in guppies. Dark and mysterious.',
    gradientFrom: '#212121',
    gradientTo: '#37474F',
    traits: ['All black', 'Hard to breed', 'Dark allure'],
    wikiSearch: 'Full Black guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Black_guppy.jpg/500px-Black_guppy.jpg',
  },
  {
    id: 'yellow-gold',
    name: 'Yellow/Gold',
    rarity: 'Uncommon',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'Gleaming golden yellow from tip to tail. Rich and warm, like a swimming piece of sunlight.',
    gradientFrom: '#F9A825',
    gradientTo: '#FDD835',
    traits: ['Golden body', 'Warm tones', 'Metallic sheen'],
    wikiSearch: 'Yellow Gold guppy',
  },
  {
    id: 'mosaic',
    name: 'Blue & Red Mosaic Delta Guppy',
    rarity: 'Common',
    category: 'Pattern Varieties',
    tailType: 'Delta',
    description: 'Blue and red patches arranged in a mosaic pattern across a wide delta tail. Every single mosaic male has a unique, unrepeatable color layout — no two fish look the same. Bred to maximize the number of distinct color patches with crisp, bold borders.',
    gradientFrom: '#1565C0',
    gradientTo: '#7B1FA2',
    traits: ['Blue & red mosaic patches', 'Every fish uniquely patterned', 'Wide delta tail'],
    wikiSearch: 'Mosaic guppy fancy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/GuppyMosaicDeltaMale.jpg/500px-GuppyMosaicDeltaMale.jpg',
  },
  {
    id: 'leopard',
    name: 'Orange Leopard Spotted Guppy',
    rarity: 'Uncommon',
    category: 'Pattern Varieties',
    tailType: 'Delta',
    description: 'Bright orange body covered in dark, irregular spots arranged in a leopard-print pattern on both the body and tail. Wild-looking and fierce, the orange leopard is bred for the most defined spots with maximum contrast against the orange base color.',
    gradientFrom: '#E65100',
    gradientTo: '#FF8A65',
    traits: ['Orange body', 'Dark leopard spots', 'High contrast wild pattern'],
    wikiSearch: 'Leopard guppy spotted',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Guppy_leopard_male.jpg/500px-Guppy_leopard_male.jpg',
  },
  {
    id: 'snakeskin-mosaic',
    name: 'Red Snakeskin Mosaic Guppy',
    rarity: 'Rare',
    category: 'Pattern Varieties',
    tailType: 'Delta',
    description: 'Vertical snakeskin markings on the body combined with a red mosaic pattern across a wide delta tail. This rare combination strain demands two of the most complex genetics in guppy breeding — the cobra-like body pattern plus the unpredictable mosaic tail.',
    gradientFrom: '#880E4F',
    gradientTo: '#B71C1C',
    traits: ['Red mosaic delta tail', 'Snakeskin body markings', 'Rare dual-pattern genetics'],
    wikiSearch: 'Snakeskin Mosaic guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Snakeskin_guppy.jpg/500px-Snakeskin_guppy.jpg',
  },
  {
    id: 'dumbo-ear',
    name: 'Orange Dumbo Ear (Elephant Ear) Guppy',
    rarity: 'Uncommon',
    category: 'Specialty Body Types',
    tailType: 'Delta',
    description: 'Vivid orange body with enormous fan-like pectoral fins that extend outward like elephant ears — up to 3× the size of normal pectoral fins. The orange coloring highlights the dramatic fins. This body mutation is the most visually unique structural trait in the entire hobby.',
    gradientFrom: '#E65100',
    gradientTo: '#FF8A65',
    traits: ['Orange body', 'Giant pectoral fins (3× normal)', 'Most unique body mutation'],
    wikiSearch: 'Dumbo Ear Elephant Ear guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Dumbo_ear_guppy_male.jpg/500px-Dumbo_ear_guppy_male.jpg',
  },
  {
    id: 'dragon-head',
    name: 'Gold & Red Dragon Head Guppy',
    rarity: 'Rare',
    category: 'Specialty Body Types',
    tailType: 'Delta',
    description: 'Red body with a metallic gold-armored head that gives the fish a fierce, dragon-like appearance. The iridescent gold head scales are a distinct genetic trait, creating a natural "helmet" effect not seen in other guppy strains.',
    gradientFrom: '#B71C1C',
    gradientTo: '#FFD54F',
    traits: ['Red body', 'Metallic gold armored head', 'Dragon-like appearance'],
    wikiSearch: 'Dragon Head guppy metallic gold red',
  },
  {
    id: 'lace-guppy',
    name: 'Blue Metallic Lace Guppy',
    rarity: 'Rare',
    category: 'Specialty Body Types',
    tailType: 'Delta',
    description: 'Silver-blue metallic body with a fine, lace-like network of lines across the delta tail — like delicate embroidery on a blue silk cloth. The metallic lace pattern is one of the most intricate and difficult tail patterns to breed for show quality.',
    gradientFrom: '#455A64',
    gradientTo: '#90CAF9',
    traits: ['Silver-blue metallic body', 'Fine lace tail network', 'Intricate show quality'],
    wikiSearch: 'Lace guppy metal blue',
  },
  {
    id: 'japanese-blue',
    name: 'Japanese Blue',
    rarity: 'Rare',
    category: 'Japanese & Asian Varieties',
    tailType: 'Delta',
    description: 'Developed in Japan, this strain features a unique blue gene that creates a deep, uniform blue body unlike any other.',
    gradientFrom: '#006064',
    gradientTo: '#00BCD4',
    traits: ['Japanese blue gene', 'Deep uniform blue', 'Unique genetics'],
    wikiSearch: 'Japanese Blue guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Japan_blue_wildtype_guppy.jpg/500px-Japan_blue_wildtype_guppy.jpg',
  },
  {
    id: 'santa-maria',
    name: 'Santa Maria Purple-Red Fancy Guppy',
    rarity: 'Rare',
    category: 'Japanese & Asian Varieties',
    tailType: 'Delta',
    description: 'Deep purple body with a rich red delta tail — a dramatic bi-color combination developed by Japanese breeders. Named after Columbus\'s flagship, this strain is bred to achieve the sharpest possible color border between the purple body and the red tail.',
    gradientFrom: '#6A1B9A',
    gradientTo: '#E53935',
    traits: ['Deep purple body', 'Rich red delta tail', 'Sharp bi-color border'],
    wikiSearch: 'Santa Maria guppy purple red',
  },
  {
    id: 'metal-head',
    name: 'Silver Metal Head Guppy',
    rarity: 'Uncommon',
    category: 'Japanese & Asian Varieties',
    tailType: 'Delta',
    description: 'Dark blue-black body with a strikingly bright silver metallic head — like the fish is wearing a polished chrome crown. The metal head trait is a Japanese-developed genetic line where the iridophores concentrate heavily on the skull, creating a mirror-like effect.',
    gradientFrom: '#546E7A',
    gradientTo: '#CFD8DC',
    traits: ['Dark body', 'Silver metallic head', 'Japanese genetic line'],
    wikiSearch: 'Metal Head guppy silver',
  },
  {
    id: 'flamingo',
    name: 'Flamingo Pink Coral Fancy Guppy',
    rarity: 'Rare',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Rose pink body with coral-orange fin edges across a wide delta tail — the color palette of a flamingo\'s plumage. Bred to achieve the softest, most saturated pink possible without crossing into red, making it one of the most delicate-looking fancy strains.',
    gradientFrom: '#E91E63',
    gradientTo: '#FF8A65',
    traits: ['Rose pink body', 'Coral-orange fin edges', 'Flamingo color palette'],
    wikiSearch: 'Flamingo pink guppy fancy delta',
  },
  {
    id: 'tiger',
    name: 'Tiger (Orange Grass)',
    rarity: 'Uncommon',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Orange with dark vertical stripes reminiscent of a tiger. Wild patterning with a grass-tail variation that resembles jungle grass.',
    gradientFrom: '#E65100',
    gradientTo: '#F9A825',
    traits: ['Orange stripes', 'Tiger pattern', 'Wild look'],
    wikiSearch: 'Tiger Orange Grass guppy',
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue (Neon Blue)',
    rarity: 'Rare',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Blazing electric blue that seems to glow under aquarium lighting. One of the most vivid colors achievable in guppies.',
    gradientFrom: '#0091EA',
    gradientTo: '#00BCD4',
    traits: ['Electric blue', 'Glowing appearance', 'Neon coloration'],
    wikiSearch: 'Electric Blue Neon guppy',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Guppy_2_Sep_65.jpg/500px-Guppy_2_Sep_65.jpg',
  },
  {
    id: 'sunrise',
    name: 'Sunrise',
    rarity: 'Rare',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Orange transitioning to golden yellow, like watching dawn break. The sunset guppy that brings warmth to any aquarium.',
    gradientFrom: '#FF6F00',
    gradientTo: '#FDD835',
    traits: ['Orange to yellow', 'Dawn colors', 'Gradient tail'],
    wikiSearch: 'Sunrise guppy orange yellow',
  },
  {
    id: 'endlers-guppy',
    name: "Endler's Guppy",
    rarity: 'Uncommon',
    category: 'Colorful Fancy Varieties',
    tailType: 'Round',
    description: "A separate species (Poecilia wingei) from Venezuela that hybridizes with common guppies. Smaller, more vivid, and incredibly active.",
    gradientFrom: '#4CAF50',
    gradientTo: '#FFC107',
    traits: ['Separate species', 'Neon colors', 'Hyperactive'],
    wikiSearch: "Endler's livebearer Poecilia wingei",
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Poecilia_wingei_Campoma_Guppy,_Campoma,_Venezuela,_male_101_de_20131123.jpg/500px-Poecilia_wingei_Campoma_Guppy,_Campoma,_Venezuela,_male_101_de_20131123.jpg',
  },
  {
    id: 'nebula',
    name: 'Purple Nebula Cosmic Fancy Guppy',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Deep indigo-purple body flecked with iridescent silver specks that mimic stars in a nebula — this strain is bred to maximize the number and brightness of these specks against the darkest possible purple background. Each fish looks like a living corner of the galaxy.',
    gradientFrom: '#0D0D2B',
    gradientTo: '#4A148C',
    traits: ['Deep indigo-purple body', 'Iridescent silver star specks', 'Galaxy-like appearance'],
    wikiSearch: 'Nebula guppy purple cosmic',
  },
  {
    id: 'galaxy-koi',
    name: 'Galaxy Koi',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Combines koi-like body patterns with a galaxy of colors. Swirling orange, black, and white in an otherworldly display.',
    gradientFrom: '#FF6F00',
    gradientTo: '#212121',
    traits: ['Koi pattern', 'Galaxy colors', 'Swirling design'],
    wikiSearch: 'Galaxy Koi guppy',
  },
  {
    id: 'red-dragon',
    name: 'Red Dragon',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Intense red body with dragon-scale metallic luster and orange accents. One of the most sought-after guppy strains.',
    gradientFrom: '#B71C1C',
    gradientTo: '#FF8F00',
    traits: ['Dragon scale luster', 'Intense red', 'Metallic sheen'],
    wikiSearch: 'Red Dragon guppy',
  },
  {
    id: 'purple-mosaic',
    name: 'Purple Mosaic',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Rich purple mosaic patterns on tail and body. Extremely difficult to breed true, making each specimen precious.',
    gradientFrom: '#4A148C',
    gradientTo: '#880E4F',
    traits: ['Purple mosaic', 'Hard to breed true', 'Precious rarity'],
    wikiSearch: 'Purple Mosaic guppy',
  },
  {
    id: 'rainbow-guppy',
    name: 'Rainbow Guppy',
    rarity: 'Ultra Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Every color of the spectrum displayed on a single fish. The holy grail of guppy breeding — almost impossible to achieve consistently.',
    gradientFrom: '#E53935',
    gradientTo: '#7C4DFF',
    traits: ['All spectrum colors', 'Breeding holy grail', 'Impossible consistency'],
    wikiSearch: 'Rainbow guppy multi-color',
  },
  {
    id: 'black-dragon',
    name: 'Black Dragon',
    rarity: 'Ultra Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'An almost black body with deep red dragon-scale highlights. The rarest and most coveted of all dragon variants.',
    gradientFrom: '#0D0D0D',
    gradientTo: '#B71C1C',
    traits: ['Near-black body', 'Red highlights', 'Rarest dragon variant'],
    wikiSearch: 'Black Dragon guppy rare',
  },

  // ── Grass / Tuxedo Variants ───────────────────────────────────────────────
  {
    id: 'blue-grass',
    name: 'Blue Grass',
    rarity: 'Uncommon',
    category: 'Grass',
    tailType: 'Delta',
    description: 'Fine, grass-like blue markings spread across a large delta tail. The intricate patterning looks like a meadow of blue blades.',
    gradientFrom: '#1565C0',
    gradientTo: '#90CAF9',
    traits: ['Grass-blade tail pattern', 'Iridescent blue', 'Large delta tail'],
    wikiSearch: 'Blue Grass guppy fancy',
  },
  {
    id: 'green-grass',
    name: 'Green Grass',
    rarity: 'Uncommon',
    category: 'Grass',
    tailType: 'Delta',
    description: 'Emerald green grass-like patterning covers the tail, creating the look of a tiny meadow in motion.',
    gradientFrom: '#2E7D32',
    gradientTo: '#A5D6A7',
    traits: ['Green grass pattern', 'Meadow appearance', 'Large tail'],
    wikiSearch: 'Green Grass guppy fancy',
  },
  {
    id: 'red-grass',
    name: 'Red Grass',
    rarity: 'Uncommon',
    category: 'Grass',
    tailType: 'Delta',
    description: 'Vivid red grass-blade markings in a large tail. The red grass has a bold, fiery quality unlike any other pattern type.',
    gradientFrom: '#C62828',
    gradientTo: '#EF9A9A',
    traits: ['Red grass pattern', 'Fiery appearance', 'Large fan tail'],
    wikiSearch: 'Red Grass guppy fancy',
  },

  // ── More Specialty Types ──────────────────────────────────────────────────
  {
    id: 'ribbon',
    name: 'Purple Ribbon Fancy Guppy',
    rarity: 'Rare',
    category: 'Tail Types',
    tailType: 'Ribbon',
    description: 'Purple-violet body with the ribbon mutation — both the dorsal and caudal fins are dramatically elongated into flowing streamers that trail twice the body length. The purple coloring makes the ribbons look like royal silk banners rippling through the water.',
    gradientFrom: '#6A1B9A',
    gradientTo: '#E1BEE7',
    traits: ['Purple-violet body', 'Ribbon-like streaming fins (2× body length)', 'Royal silk appearance'],
    wikiSearch: 'Ribbon guppy fancy long fin purple',
  },
  {
    id: 'panda',
    name: 'Panda Guppy',
    rarity: 'Uncommon',
    category: 'Pattern',
    tailType: 'Delta',
    description: 'High-contrast black and white patterning that mimics the markings of a giant panda. Charming and instantly recognizable.',
    gradientFrom: '#212121',
    gradientTo: '#F5F5F5',
    traits: ['Black & white pattern', 'Panda-like markings', 'High contrast'],
    wikiSearch: 'Panda guppy black white fancy',
  },
  {
    id: 'albino-blue',
    name: 'Albino Blue',
    rarity: 'Rare',
    category: 'Solid Color',
    tailType: 'Delta',
    description: 'Albino genetics applied to blue strains produce a soft, ethereal blue with pink-red eyes. Delicate and otherworldly in appearance.',
    gradientFrom: '#90CAF9',
    gradientTo: '#E3F2FD',
    traits: ['Albino eyes', 'Soft blue tones', 'Ethereal look'],
    wikiSearch: 'Albino Blue guppy fancy',
  },
  {
    id: 'albino-mosaic',
    name: 'Albino Mosaic',
    rarity: 'Rare',
    category: 'Pattern',
    tailType: 'Delta',
    description: 'The mosaic pattern in albino form — pastel, washed-out blotches on a pink-cream body. Looks like a watercolor painting.',
    gradientFrom: '#F8BBD0',
    gradientTo: '#CE93D8',
    traits: ['Albino mosaic pattern', 'Pastel coloring', 'Watercolor effect'],
    wikiSearch: 'Albino Mosaic guppy fancy',
  },
  {
    id: 'yellow-lace',
    name: 'Yellow Lace',
    rarity: 'Rare',
    category: 'Pattern',
    tailType: 'Delta',
    description: 'Delicate yellow lace-like patterns on tail and fins. The intricate network of fine lines creates a textile quality.',
    gradientFrom: '#F9A825',
    gradientTo: '#FFF9C4',
    traits: ['Yellow lace pattern', 'Intricate detail', 'Textile-like quality'],
    wikiSearch: 'Yellow Lace guppy fancy',
  },
  {
    id: 'purple-dragon',
    name: 'Purple Dragon',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Purple dragon-scale metallic patterning on the body and fins. A rare combination of the dragon gene and purple coloring.',
    gradientFrom: '#4A148C',
    gradientTo: '#CE93D8',
    traits: ['Purple dragon scales', 'Metallic sheen', 'Rare color combo'],
    wikiSearch: 'Purple Dragon guppy metallic',
  },
  {
    id: 'emerald',
    name: 'Emerald Guppy',
    rarity: 'Uncommon',
    category: 'Solid Color',
    tailType: 'Delta',
    description: 'Rich emerald green covering body and fins with a gemstone-like depth of color. Stunning against a planted tank background.',
    gradientFrom: '#1B5E20',
    gradientTo: '#69F0AE',
    traits: ['Gemstone green', 'Deep color saturation', 'Planted tank star'],
    wikiSearch: 'Emerald green guppy fancy',
  },
  {
    id: 'tequila-sunrise',
    name: 'Tequila Sunrise',
    rarity: 'Rare',
    category: 'Fancy',
    tailType: 'Delta',
    description: 'Named after the cocktail — a gradient of red at the base fading through orange to yellow at the fin tips, exactly like the layered drink.',
    gradientFrom: '#D32F2F',
    gradientTo: '#FDD835',
    traits: ['Red-orange-yellow gradient', 'Cocktail inspired', 'Smooth color fade'],
    wikiSearch: 'Tequila Sunrise guppy gradient',
  },
  {
    id: 'vienna-turquoise',
    name: 'Vienna Turquoise',
    rarity: 'Rare',
    category: 'Asian Strain',
    tailType: 'Delta',
    description: 'Developed by Viennese breeders, this strain features a bright turquoise sheen that is distinct from standard blues and greens.',
    gradientFrom: '#006064',
    gradientTo: '#80DEEA',
    traits: ['Turquoise iridescence', 'Viennese origin', 'Distinct blue-green'],
    wikiSearch: 'Vienna Turquoise guppy fancy',
  },
  {
    id: 'ice-blue',
    name: 'Ice Blue',
    rarity: 'Rare',
    category: 'Solid Color',
    tailType: 'Delta',
    description: 'A pale, frosty blue that looks like it was dipped in glacial water. Cool and crystalline — exceptional in a minimalist aquascape.',
    gradientFrom: '#B3E5FC',
    gradientTo: '#E1F5FE',
    traits: ['Frosty pale blue', 'Crystalline appearance', 'Glacial color'],
    wikiSearch: 'Ice Blue guppy pale fancy',
  },
  {
    id: 'magenta',
    name: 'Magenta Guppy',
    rarity: 'Rare',
    category: 'Solid Color',
    tailType: 'Delta',
    description: 'A striking magenta-pink that sits between red and purple on the spectrum. Bold and saturated, this color stops you in your tracks.',
    gradientFrom: '#AD1457',
    gradientTo: '#F48FB1',
    traits: ['True magenta color', 'Bold saturation', 'Eye-catching'],
    wikiSearch: 'Magenta pink guppy fancy',
  },
  {
    id: 'coral',
    name: 'Coral Guppy',
    rarity: 'Rare',
    category: 'Solid Color',
    tailType: 'Delta',
    description: 'A warm coral-orange that evokes tropical reefs. Softer than full red, with peachy undertones that glow under LED lighting.',
    gradientFrom: '#FF7043',
    gradientTo: '#FFCCBC',
    traits: ['Warm coral tone', 'Reef-inspired', 'Glows under LED'],
    wikiSearch: 'Coral orange guppy fancy',
  },
  {
    id: 'steel-blue',
    name: 'Steel Blue',
    rarity: 'Uncommon',
    category: 'Solid Color',
    tailType: 'Delta',
    description: 'A deep, muted steel-gray blue reminiscent of polished metal. Less flashy than electric blue but sophisticated and unique.',
    gradientFrom: '#455A64',
    gradientTo: '#90A4AE',
    traits: ['Muted steel tone', 'Sophisticated look', 'Metal-like sheen'],
    wikiSearch: 'Steel Blue guppy fancy metallic',
  },
  {
    id: 'bronze',
    name: 'Bronze Guppy',
    rarity: 'Uncommon',
    category: 'Solid Color',
    tailType: 'Delta',
    description: 'Warm bronze and copper tones cover the body, glinting like old coins in the light. An understated, elegant strain.',
    gradientFrom: '#6D4C41',
    gradientTo: '#FFCCBC',
    traits: ['Bronze-copper tone', 'Coin-like glint', 'Warm elegance'],
    wikiSearch: 'Bronze copper guppy fancy',
  },
  {
    id: 'half-black-green',
    name: 'Half Black Green',
    rarity: 'Rare',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'Vivid green front half against a velvet black rear — the hardest half-black color to achieve with a clean midline.',
    gradientFrom: '#1B5E20',
    gradientTo: '#212121',
    traits: ['Green front half', 'Black rear half', 'Hardest half-black variety'],
    wikiSearch: 'Half Black Green guppy fancy',
  },
  {
    id: 'moscow-red',
    name: 'Moscow Red',
    rarity: 'Rare',
    category: 'Moscow',
    tailType: 'Delta',
    description: 'The rarest of the Moscow line — a deep, full-body crimson red with the characteristic iridescent Moscow sheen.',
    gradientFrom: '#B71C1C',
    gradientTo: '#E53935',
    traits: ['Full-body crimson', 'Moscow iridescence', 'Very rare line'],
    wikiSearch: 'Moscow Red guppy fancy',
  },
  {
    id: 'poecilia-obscura',
    name: 'Poecilia Obscura',
    rarity: 'Very Rare',
    category: 'Species',
    tailType: 'Small Fan',
    description: 'A newly described guppy species from Trinidad, similar to the common guppy but genetically distinct. Extremely rare in the hobby.',
    gradientFrom: '#37474F',
    gradientTo: '#80CBC4',
    traits: ['Separate species', 'Recently described', 'Trinidad origin'],
    wikiSearch: 'Poecilia obscura guppy Trinidad',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Poecilia_reticulata_01.jpg/500px-Poecilia_reticulata_01.jpg',
  },
];
