export type Rarity = 'Common' | 'Uncommon' | 'Rare' | 'Very Rare' | 'Ultra Rare';

export interface GuppyStrain {
  id: string;
  name: string;
  rarity: Rarity;
  category: string;
  tailType: string;
  description: string;
  gradientFrom: string;
  gradientTo: string;
  traits: string[];
  wikiSearch: string;
  photoUrl?: string;  // direct URL when a real photo has been sourced
}

export const guppyStrains: GuppyStrain[] = [
  {
    id: 'wild-type',
    name: 'Wild Type',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Round/Fan',
    description: 'The original guppy from Trinidad. Males display brilliant random color patterns that inspired all modern fancy strains.',
    gradientFrom: '#1B5E20',
    gradientTo: '#4CAF50',
    traits: ['Random color spots', 'Iridescent scales', 'Fan tail'],
    wikiSearch: 'Poecilia reticulata wild male',
  },
  {
    id: 'delta-tail',
    name: 'Delta Tail (Fan Tail)',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Delta/Fan',
    description: 'The iconic fan-shaped tail spreads wide like a delta wing. A classic show guppy beloved by hobbyists worldwide.',
    gradientFrom: '#1565C0',
    gradientTo: '#42A5F5',
    traits: ['Wide fan tail', 'Show quality', 'Vivid colors'],
    wikiSearch: 'fancy delta tail guppy',
  },
  {
    id: 'veil-tail',
    name: 'Veil Tail',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Veil',
    description: 'Flowing and graceful, the veil tail drapes like fine silk through the water. Ethereal beauty in motion.',
    gradientFrom: '#4A148C',
    gradientTo: '#9C27B0',
    traits: ['Long flowing tail', 'Silky appearance', 'Graceful movement'],
    wikiSearch: 'veil tail guppy',
  },
  {
    id: 'round-tail',
    name: 'Round Tail',
    rarity: 'Common',
    category: 'Classic Tail Types',
    tailType: 'Round',
    description: 'A perfectly circular tail gives this guppy a balanced, symmetrical beauty. Clean and classic.',
    gradientFrom: '#00695C',
    gradientTo: '#4DB6AC',
    traits: ['Circular tail', 'Symmetrical', 'Classic look'],
    wikiSearch: 'round tail guppy',
  },
  {
    id: 'double-sword-tail',
    name: 'Double Sword Tail',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Double Sword',
    description: 'Twin sword-like extensions grace the top and bottom of the tail, creating a dramatic X-shaped silhouette.',
    gradientFrom: '#F9A825',
    gradientTo: '#FFF176',
    traits: ['Twin sword extensions', 'Top and bottom swords', 'Dramatic silhouette'],
    wikiSearch: 'double sword tail guppy',
  },
  {
    id: 'top-sword-tail',
    name: 'Top Sword Tail',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Top Sword',
    description: 'A single sword extension shoots upward from the tail, like a fin piercing the sky.',
    gradientFrom: '#EF6C00',
    gradientTo: '#FFB74D',
    traits: ['Upper sword extension', 'Asymmetric tail', 'Bold profile'],
    wikiSearch: 'top sword guppy',
  },
  {
    id: 'bottom-sword-tail',
    name: 'Bottom Sword Tail',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Bottom Sword',
    description: 'A sword extension drops downward from the caudal fin, creating an elegant downward sweep.',
    gradientFrom: '#1976D2',
    gradientTo: '#64B5F6',
    traits: ['Lower sword extension', 'Downward sweep', 'Elegant profile'],
    wikiSearch: 'bottom sword guppy',
  },
  {
    id: 'lyretail',
    name: 'Lyretail',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Lyre',
    description: 'Named after the ancient stringed instrument, the lyretail features elegant curved lobes that arch gracefully outward.',
    gradientFrom: '#6A1B9A',
    gradientTo: '#CE93D8',
    traits: ['Curved lobes', 'Lyre shape', 'Musical elegance'],
    wikiSearch: 'lyretail guppy',
  },
  {
    id: 'spear-tail',
    name: 'Spear Tail',
    rarity: 'Uncommon',
    category: 'Classic Tail Types',
    tailType: 'Spear',
    description: "The spear tail comes to a single sharp point, like a warrior's weapon slicing through water.",
    gradientFrom: '#00695C',
    gradientTo: '#80CBC4',
    traits: ['Pointed tip', 'Elongated center', 'Streamlined'],
    wikiSearch: 'spear tail guppy',
  },
  {
    id: 'coffertail',
    name: 'Coffertail',
    rarity: 'Rare',
    category: 'Classic Tail Types',
    tailType: 'Coffer',
    description: 'A uniquely shaped tail with a flat top and rounded bottom, resembling an ornate treasure chest.',
    gradientFrom: '#FF8F00',
    gradientTo: '#FFD54F',
    traits: ['Flat-top tail', 'Distinct shape', 'Rare form'],
    wikiSearch: 'coffertail guppy',
  },
  {
    id: 'pintail',
    name: 'Pintail (Needle Tail)',
    rarity: 'Rare',
    category: 'Classic Tail Types',
    tailType: 'Pin/Needle',
    description: 'Tapers to a fine needle-like point. Sleek, minimalist, and strikingly different from typical fancy guppies.',
    gradientFrom: '#37474F',
    gradientTo: '#90A4AE',
    traits: ['Needle point', 'Minimalist', 'Sleek profile'],
    wikiSearch: 'pintail needle guppy',
  },
  {
    id: 'flag-tail',
    name: 'Flag Tail',
    rarity: 'Rare',
    category: 'Classic Tail Types',
    tailType: 'Flag',
    description: 'The tail resembles a waving flag, with a distinctive trailing edge that flutters as the fish swims.',
    gradientFrom: '#BF360C',
    gradientTo: '#FF8A65',
    traits: ['Flag-like shape', 'Fluttering motion', 'Distinctive trailing edge'],
    wikiSearch: 'flag tail guppy',
  },
  {
    id: 'moscow-blue',
    name: 'Moscow Blue',
    rarity: 'Uncommon',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'Developed in Russia, this strain displays an intense solid blue body that shimmers like a night sky.',
    gradientFrom: '#0D47A1',
    gradientTo: '#1565C0',
    traits: ['Solid blue body', 'Russian strain', 'Intense coloration'],
    wikiSearch: 'Moscow Blue guppy',
  },
  {
    id: 'moscow-green',
    name: 'Moscow Green',
    rarity: 'Uncommon',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'A rich, jewel-toned green body makes this Russian strain one of the most visually striking guppies available.',
    gradientFrom: '#1B5E20',
    gradientTo: '#2E7D32',
    traits: ['Solid green body', 'Jewel-toned', 'Russian origin'],
    wikiSearch: 'Moscow Green guppy',
  },
  {
    id: 'moscow-purple',
    name: 'Moscow Purple',
    rarity: 'Rare',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'A deep purple body, rare among fish. This Moscow strain commands attention in any tank.',
    gradientFrom: '#4A148C',
    gradientTo: '#6A1B9A',
    traits: ['Deep purple body', 'Head-to-tail color', 'Show quality'],
    wikiSearch: 'Moscow Purple guppy',
  },
  {
    id: 'black-moscow',
    name: 'Black Moscow',
    rarity: 'Rare',
    category: 'Moscow Strains',
    tailType: 'Delta',
    description: 'Nearly pitch black with a blue iridescent sheen. The Black Moscow is hauntingly beautiful and difficult to breed true.',
    gradientFrom: '#212121',
    gradientTo: '#1A237E',
    traits: ['Jet black body', 'Blue iridescence', 'Hard to breed true'],
    wikiSearch: 'Black Moscow guppy',
  },
  {
    id: 'yellow-cobra',
    name: 'Yellow Cobra',
    rarity: 'Common',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Bright yellow with vertical snake-like markings on the body. Vibrant and eye-catching with the classic cobra pattern.',
    gradientFrom: '#F57F17',
    gradientTo: '#FFF176',
    traits: ['Yellow body', 'Snake markings', 'Vertical stripes'],
    wikiSearch: 'Yellow Cobra guppy snakeskin',
  },
  {
    id: 'red-cobra',
    name: 'Red Cobra',
    rarity: 'Common',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Fiery red with the distinctive cobra snakeskin pattern. Bold and aggressive-looking, a crowd favorite.',
    gradientFrom: '#B71C1C',
    gradientTo: '#EF5350',
    traits: ['Red body', 'Cobra pattern', 'Bold presence'],
    wikiSearch: 'Red Cobra guppy',
  },
  {
    id: 'green-cobra',
    name: 'Green Cobra',
    rarity: 'Uncommon',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Vivid green scales arranged in the cobra pattern. Like a tiny jungle serpent, exotic and vibrant.',
    gradientFrom: '#2E7D32',
    gradientTo: '#81C784',
    traits: ['Green scales', 'Cobra pattern', 'Exotic look'],
    wikiSearch: 'Green Cobra guppy',
  },
  {
    id: 'blue-cobra',
    name: 'Blue Cobra',
    rarity: 'Uncommon',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'Electric blue with snake-like body markings. Cool, mysterious, and one of the most popular cobra varieties.',
    gradientFrom: '#1A237E',
    gradientTo: '#5C6BC0',
    traits: ['Blue body', 'Snake pattern', 'Electric sheen'],
    wikiSearch: 'Blue Cobra guppy',
  },
  {
    id: 'king-cobra',
    name: 'King Cobra',
    rarity: 'Rare',
    category: 'Cobra / Snakeskin',
    tailType: 'Delta',
    description: 'The regal king of cobra guppies. Combines deep purple and gold in an intricate snakeskin pattern fit for royalty.',
    gradientFrom: '#4A148C',
    gradientTo: '#FF8F00',
    traits: ['Purple & gold', 'Complex pattern', 'Royal appearance'],
    wikiSearch: 'King Cobra guppy',
  },
  {
    id: 'blue-tuxedo',
    name: 'Blue Tuxedo',
    rarity: 'Common',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'The classic tuxedo pattern in blue: front half lighter, back half deep blue, like wearing formal attire.',
    gradientFrom: '#1A237E',
    gradientTo: '#0277BD',
    traits: ['Two-tone body', 'Tuxedo pattern', 'Blue coloration'],
    wikiSearch: 'Blue Tuxedo guppy',
  },
  {
    id: 'red-tuxedo',
    name: 'Red Tuxedo',
    rarity: 'Common',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'A bold red tuxedo pattern with a dark rear half. Dramatic contrast that makes this fish pop in any tank.',
    gradientFrom: '#B71C1C',
    gradientTo: '#4A148C',
    traits: ['Red & dark contrast', 'Tuxedo pattern', 'Bold look'],
    wikiSearch: 'Red Tuxedo guppy',
  },
  {
    id: 'yellow-tuxedo',
    name: 'Yellow Tuxedo',
    rarity: 'Uncommon',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'Sunny yellow front with a dark navy tuxedo back. Cheerful yet sophisticated, this is a show-stopper.',
    gradientFrom: '#F57F17',
    gradientTo: '#1A237E',
    traits: ['Yellow & navy', 'Tuxedo pattern', 'Cheerful colors'],
    wikiSearch: 'Yellow Tuxedo guppy',
  },
  {
    id: 'neon-tuxedo',
    name: 'Neon Tuxedo',
    rarity: 'Rare',
    category: 'Tuxedo Pattern',
    tailType: 'Delta',
    description: 'The tuxedo pattern taken to the extreme with neon electric colors that seem to glow under aquarium lights.',
    gradientFrom: '#006064',
    gradientTo: '#00E5FF',
    traits: ['Neon coloration', 'Electric appearance', 'Glows under light'],
    wikiSearch: 'Neon Tuxedo guppy electric',
  },
  {
    id: 'half-black-blue',
    name: 'Half Black Blue',
    rarity: 'Uncommon',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'The rear half of the body is jet black, the front a vivid blue. A striking two-tone masterpiece.',
    gradientFrom: '#1A237E',
    gradientTo: '#424242',
    traits: ['Half black', 'Blue front', 'Sharp contrast'],
    wikiSearch: 'Half Black Blue guppy',
  },
  {
    id: 'half-black-red',
    name: 'Half Black Red',
    rarity: 'Uncommon',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'The classic half-black pattern in red. The fiery front against the black rear creates a dramatic fire-and-darkness look.',
    gradientFrom: '#B71C1C',
    gradientTo: '#212121',
    traits: ['Half black', 'Red front', 'Fire contrast'],
    wikiSearch: 'Half Black Red guppy',
  },
  {
    id: 'half-black-purple',
    name: 'Half Black Purple',
    rarity: 'Rare',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'Deep royal purple meets jet black in this striking half-black variety. Mysterious and regal.',
    gradientFrom: '#4A148C',
    gradientTo: '#212121',
    traits: ['Half black', 'Purple front', 'Regal look'],
    wikiSearch: 'Half Black Purple guppy',
  },
  {
    id: 'half-black-yellow',
    name: 'Half Black Yellow',
    rarity: 'Uncommon',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'Bright sunny yellow meets the dark abyss in this half-black strain. High contrast and visually stunning.',
    gradientFrom: '#F57F17',
    gradientTo: '#212121',
    traits: ['Half black', 'Yellow front', 'High contrast'],
    wikiSearch: 'Half Black Yellow guppy',
  },
  {
    id: 'half-black-pastel',
    name: 'Half Black Pastel',
    rarity: 'Rare',
    category: 'Half Black',
    tailType: 'Delta',
    description: 'Soft pastel shades on the front half transition dramatically to solid black. Delicate yet striking.',
    gradientFrom: '#880E4F',
    gradientTo: '#212121',
    traits: ['Half black', 'Pastel colors', 'Soft to stark contrast'],
    wikiSearch: 'Half Black Pastel guppy',
  },
  {
    id: 'full-red',
    name: 'Full Red',
    rarity: 'Common',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'Entirely covered in vibrant red from nose to tail. A true red guppy with no other colors — simple perfection.',
    gradientFrom: '#C62828',
    gradientTo: '#E53935',
    traits: ['All red body', 'Uniform color', 'Show standard'],
    wikiSearch: 'Full Red guppy',
  },
  {
    id: 'albino-full-red',
    name: 'Albino Full Red',
    rarity: 'Rare',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'The albino form of the Full Red — pink-red body with striking red eyes. Rare and uniquely beautiful.',
    gradientFrom: '#FF80AB',
    gradientTo: '#FF6090',
    traits: ['Albino form', 'Red eyes', 'Pink-red coloration'],
    wikiSearch: 'Albino Full Red guppy',
  },
  {
    id: 'platinum',
    name: 'Platinum (Full White)',
    rarity: 'Uncommon',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'A pristine, metallic white or platinum body that gleams like polished silver. Pure elegance.',
    gradientFrom: '#9E9E9E',
    gradientTo: '#ECEFF1',
    traits: ['Metallic white', 'Silver sheen', 'Pure elegance'],
    wikiSearch: 'Platinum White guppy',
  },
  {
    id: 'full-black',
    name: 'Full Black',
    rarity: 'Rare',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'Completely black from head to tail — one of the hardest colors to achieve in guppies. Dark and mysterious.',
    gradientFrom: '#212121',
    gradientTo: '#37474F',
    traits: ['All black', 'Hard to breed', 'Dark allure'],
    wikiSearch: 'Full Black guppy',
  },
  {
    id: 'yellow-gold',
    name: 'Yellow/Gold',
    rarity: 'Uncommon',
    category: 'Solid / Block Colors',
    tailType: 'Delta',
    description: 'Gleaming golden yellow from tip to tail. Rich and warm, like a swimming piece of sunlight.',
    gradientFrom: '#F9A825',
    gradientTo: '#FDD835',
    traits: ['Golden body', 'Warm tones', 'Metallic sheen'],
    wikiSearch: 'Yellow Gold guppy',
  },
  {
    id: 'mosaic',
    name: 'Mosaic',
    rarity: 'Common',
    category: 'Pattern Varieties',
    tailType: 'Delta',
    description: 'A patchwork of multiple colors arranged in a mosaic pattern across the tail. Each fish is a unique living artwork.',
    gradientFrom: '#1565C0',
    gradientTo: '#7B1FA2',
    traits: ['Multi-color patches', 'Unique pattern each fish', 'Living artwork'],
    wikiSearch: 'Mosaic guppy fancy',
  },
  {
    id: 'leopard',
    name: 'Leopard',
    rarity: 'Uncommon',
    category: 'Pattern Varieties',
    tailType: 'Delta',
    description: 'Dark spots on an orange body create a leopard-print effect. Wild, fierce, and surprisingly rare in guppies.',
    gradientFrom: '#E65100',
    gradientTo: '#212121',
    traits: ['Spotted pattern', 'Leopard print', 'Wild appearance'],
    wikiSearch: 'Leopard guppy spotted',
  },
  {
    id: 'snakeskin-mosaic',
    name: 'Snakeskin Mosaic',
    rarity: 'Rare',
    category: 'Pattern Varieties',
    tailType: 'Delta',
    description: 'The combination of snakeskin body markings with mosaic tail coloring creates an extraordinarily complex pattern.',
    gradientFrom: '#880E4F',
    gradientTo: '#1A237E',
    traits: ['Snakeskin + mosaic', 'Complex pattern', 'Rare combination'],
    wikiSearch: 'Snakeskin Mosaic guppy',
  },
  {
    id: 'dumbo-ear',
    name: 'Dumbo Ear (Elephant Ear)',
    rarity: 'Uncommon',
    category: 'Specialty Body Types',
    tailType: 'Delta',
    description: 'Massive, fan-like pectoral fins extend outward like elephant ears. Unusual and endearing — unlike any other guppy.',
    gradientFrom: '#E65100',
    gradientTo: '#0277BD',
    traits: ['Giant pectoral fins', 'Elephant ear shape', 'Unique body type'],
    wikiSearch: 'Dumbo Ear Elephant Ear guppy',
  },
  {
    id: 'dragon-head',
    name: 'Dragon Head',
    rarity: 'Rare',
    category: 'Specialty Body Types',
    tailType: 'Delta',
    description: 'A metallic, armored-looking head gives this guppy a dragon-like appearance. Fierce and fantastical.',
    gradientFrom: '#B71C1C',
    gradientTo: '#FFD54F',
    traits: ['Metallic head', 'Armored look', 'Dragon appearance'],
    wikiSearch: 'Dragon Head guppy metallic',
  },
  {
    id: 'lace-guppy',
    name: 'Lace Guppy',
    rarity: 'Rare',
    category: 'Specialty Body Types',
    tailType: 'Delta',
    description: 'Fine, lace-like patterns cover the tail, resembling delicate lacework. Intricate and refined beauty.',
    gradientFrom: '#455A64',
    gradientTo: '#B0BEC5',
    traits: ['Lace tail pattern', 'Fine detail', 'Refined beauty'],
    wikiSearch: 'Lace guppy metal',
  },
  {
    id: 'japanese-blue',
    name: 'Japanese Blue',
    rarity: 'Rare',
    category: 'Japanese & Asian Varieties',
    tailType: 'Delta',
    description: 'Developed in Japan, this strain features a unique blue gene that creates a deep, uniform blue body unlike any other.',
    gradientFrom: '#006064',
    gradientTo: '#00BCD4',
    traits: ['Japanese blue gene', 'Deep uniform blue', 'Unique genetics'],
    wikiSearch: 'Japanese Blue guppy',
  },
  {
    id: 'santa-maria',
    name: 'Santa Maria',
    rarity: 'Rare',
    category: 'Japanese & Asian Varieties',
    tailType: 'Delta',
    description: "A Japanese strain featuring rich purple and red coloration. Named after Christopher Columbus's ship, this guppy is a true explorer of beauty.",
    gradientFrom: '#6A1B9A',
    gradientTo: '#E53935',
    traits: ['Purple & red', 'Japanese breeding', 'Bold bi-color'],
    wikiSearch: 'Santa Maria guppy',
  },
  {
    id: 'metal-head',
    name: 'Metal Head',
    rarity: 'Uncommon',
    category: 'Japanese & Asian Varieties',
    tailType: 'Delta',
    description: 'The head appears metallic gold or silver, creating a striking contrast with the body. Like wearing a crown.',
    gradientFrom: '#546E7A',
    gradientTo: '#CFD8DC',
    traits: ['Metallic head', 'Crown-like effect', 'Silver/gold head'],
    wikiSearch: 'Metal Head guppy',
  },
  {
    id: 'flamingo',
    name: 'Flamingo',
    rarity: 'Rare',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Brilliant pink and coral tones give this guppy the look of its namesake bird. Delicate, tropical, and stunning.',
    gradientFrom: '#E91E63',
    gradientTo: '#FF8A65',
    traits: ['Pink coloration', 'Coral tones', 'Tropical look'],
    wikiSearch: 'Flamingo pink guppy',
  },
  {
    id: 'tiger',
    name: 'Tiger (Orange Grass)',
    rarity: 'Uncommon',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Orange with dark vertical stripes reminiscent of a tiger. Wild patterning with a grass-tail variation that resembles jungle grass.',
    gradientFrom: '#E65100',
    gradientTo: '#F9A825',
    traits: ['Orange stripes', 'Tiger pattern', 'Wild look'],
    wikiSearch: 'Tiger Orange Grass guppy',
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue (Neon Blue)',
    rarity: 'Rare',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Blazing electric blue that seems to glow under aquarium lighting. One of the most vivid colors achievable in guppies.',
    gradientFrom: '#0091EA',
    gradientTo: '#00BCD4',
    traits: ['Electric blue', 'Glowing appearance', 'Neon coloration'],
    wikiSearch: 'Electric Blue Neon guppy',
  },
  {
    id: 'sunrise',
    name: 'Sunrise',
    rarity: 'Rare',
    category: 'Colorful Fancy Varieties',
    tailType: 'Delta',
    description: 'Orange transitioning to golden yellow, like watching dawn break. The sunset guppy that brings warmth to any aquarium.',
    gradientFrom: '#FF6F00',
    gradientTo: '#FDD835',
    traits: ['Orange to yellow', 'Dawn colors', 'Gradient tail'],
    wikiSearch: 'Sunrise guppy orange yellow',
  },
  {
    id: 'endlers-guppy',
    name: "Endler's Guppy",
    rarity: 'Uncommon',
    category: 'Colorful Fancy Varieties',
    tailType: 'Round',
    description: "A separate species (Poecilia wingei) from Venezuela that hybridizes with common guppies. Smaller, more vivid, and incredibly active.",
    gradientFrom: '#4CAF50',
    gradientTo: '#FFC107',
    traits: ['Separate species', 'Neon colors', 'Hyperactive'],
    wikiSearch: "Endler's livebearer Poecilia wingei",
  },
  {
    id: 'nebula',
    name: 'Nebula',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Deep cosmic purple and black with iridescent specks like stars. Swimming through your tank like a living nebula.',
    gradientFrom: '#0D0D2B',
    gradientTo: '#4A148C',
    traits: ['Cosmic coloration', 'Star-like specks', 'Deep purple'],
    wikiSearch: 'Nebula guppy purple cosmic',
  },
  {
    id: 'galaxy-koi',
    name: 'Galaxy Koi',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Combines koi-like body patterns with a galaxy of colors. Swirling orange, black, and white in an otherworldly display.',
    gradientFrom: '#FF6F00',
    gradientTo: '#212121',
    traits: ['Koi pattern', 'Galaxy colors', 'Swirling design'],
    wikiSearch: 'Galaxy Koi guppy',
  },
  {
    id: 'red-dragon',
    name: 'Red Dragon',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Intense red body with dragon-scale metallic luster and orange accents. One of the most sought-after guppy strains.',
    gradientFrom: '#B71C1C',
    gradientTo: '#FF8F00',
    traits: ['Dragon scale luster', 'Intense red', 'Metallic sheen'],
    wikiSearch: 'Red Dragon guppy',
  },
  {
    id: 'purple-mosaic',
    name: 'Purple Mosaic',
    rarity: 'Very Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Rich purple mosaic patterns on tail and body. Extremely difficult to breed true, making each specimen precious.',
    gradientFrom: '#4A148C',
    gradientTo: '#880E4F',
    traits: ['Purple mosaic', 'Hard to breed true', 'Precious rarity'],
    wikiSearch: 'Purple Mosaic guppy',
  },
  {
    id: 'rainbow-guppy',
    name: 'Rainbow Guppy',
    rarity: 'Ultra Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'Every color of the spectrum displayed on a single fish. The holy grail of guppy breeding — almost impossible to achieve consistently.',
    gradientFrom: '#E53935',
    gradientTo: '#7C4DFF',
    traits: ['All spectrum colors', 'Breeding holy grail', 'Impossible consistency'],
    wikiSearch: 'Rainbow guppy multi-color',
  },
  {
    id: 'black-dragon',
    name: 'Black Dragon',
    rarity: 'Ultra Rare',
    category: 'Ultra Rare / Show Strains',
    tailType: 'Delta',
    description: 'An almost black body with deep red dragon-scale highlights. The rarest and most coveted of all dragon variants.',
    gradientFrom: '#0D0D0D',
    gradientTo: '#B71C1C',
    traits: ['Near-black body', 'Red highlights', 'Rarest dragon variant'],
    wikiSearch: 'Black Dragon guppy rare',
  },
];
